const PARTICIPANTS = [
  {id:'01',name:'Esmeralda Cordero',club:false},
  {id:'02',name:'Bete Leme',club:false},
  {id:'03',name:'Nacho Bautista',club:false},
  {id:'04',name:'Chiara Garofalo',club:false},
  {id:'05',name:'Eva Moreira',club:false},
  {id:'06',name:'Sara Lopes',club:false},
  {id:'07',name:'MemeAlboran25',club:false},
  {id:'08',name:'Andrea Padilla',club:false},
  {id:'09',name:'Jeni Serrano',club:false},
  {id:'10',name:'Silvia Ramirez',club:false},
  {id:'11',name:'Sheila Arakaki',club:false},
  {id:'12',name:'Gisele dos Santos',club:false},
  {id:'13',name:'Claudia Cienfuegos',club:false},
  {id:'14',name:'Marina Rodríguez',club:false},
  {id:'15',name:'Shirley Mary',club:false},
  {id:'16',name:'Tabita Yaranga',club:false},
  {id:'17',name:'Adriana Ruiz',club:false},
  {id:'18',name:'Rosana Quintana',club:false},
  {id:'19',name:'Lídia Lopes',club:false},
  {id:'20',name:'Sole Oyarbide',club:false},
  {id:'21',name:'Marcele Morais',club:false},
  {id:'22',name:'Ivonny Alves',club:false},
  {id:'23',name:'Juliane Rodrigues',club:false},
  {id:'24',name:'Lise Ferrari',club:false},
  {id:'25',name:'Virginia Sayago',club:false},
  {id:'26',name:'Licelle Joy Libunao',club:false},
  {id:'27',name:'Andreza Carolliny',club:false},
  {id:'28',name:'Carlos Machado',club:false},
  {id:'29',name:'Bianca Rosetti',club:false},
  {id:'30',name:'Flavia Amorim',club:false},
  {id:'31',name:'Nattália Azevedo',club:false},
  {id:'32',name:'Carla Barroso',club:false},
  {id:'33',name:'María José Delgado',club:false},
  {id:'34',name:'Mey Lee Maulén',club:false},
  {id:'35',name:'Alejandro Elias',club:false},
  {id:'36',name:'Daisy Rodríguez',club:false},
  {id:'37',name:'Laura del Barrio',club:false},
  {id:'38',name:'Pamy Urbina',club:false},
  {id:'39',name:'Marcos Domingues',club:false},
  {id:'40',name:'Flavia Martin',club:false},
  {id:'41',name:'Camila Llerena',club:false},
  {id:'42',name:'Raquel Gómez',club:false},
  {id:'43',name:'Novias Alborán Argentina',club:true},
  {id:'44',name:'Club de fans Ecuador',club:true},
  {id:'45',name:'Familia Alborán Argentina Rosario',club:true},
  {id:'46',name:'Legión Alborán Brasil',club:true}
];
